substitutions:
  _SERVICE_NAME: monhub
  _REGION: asia-northeast1
  _ARTIFACT_REPOSITORY: monhub-registry
  _IMAGE_NAME: monhub-app
  _GO_VERSION: "1.24"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: UNSPECIFIED

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "-t"
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - "-t"
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:latest'
      - "-f"
      - "Dockerfile"
      - "--build-arg"
      - "GO_VERSION=${_GO_VERSION}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - "push"
      - "--all-tags"
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}'
    waitFor: ["build-image"]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--ingress"
      - "all"
      - "--port"
      - "8080"
      - "--timeout"
      - "3600"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--concurrency"
      - "10"
      - "--update-env-vars"
      - "PROJECT_ID=$PROJECT_ID,LOCATION=${_REGION}"
    waitFor: ["push-image"]

artifacts:
  images:
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:latest'

timeout: "1800s"
