# fly.toml app configuration file generated for mhp-rooms on 2025-06-17T15:12:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mhp-rooms'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
